language: csharp
mono: none
dotnet: 2.0
branches:
  only:
    - master
script:
 - dotnet build ./src/backend/NewsTrack.sln
 - dotnet test ./src/backend/NewsTrack.Browser.IntegrationTests/NewsTrack.Browser.IntegrationTests.csproj
 - dotnet test ./src/backend/NewsTrack.Common.UnitTests/NewsTrack.Common.UnitTests.csproj
 - dotnet test ./src/backend/NewsTrack.Domain.UnitTests/NewsTrack.Domain.UnitTests.csproj
 - dotnet test ./src/backend/NewsTrack.Identity.UnitTests/NewsTrack.Identity.UnitTests.csproj
 - dotnet test ./src/backend/NewsTrack.WebApi.UnitTests/NewsTrack.WebApi.UnitTests.csproj
